FROM nvcr.io/nvidia/tensorrt:25.01-py3

RUN echo "coloredlogs==15.0.1 \
flatbuffers==25.2.10 \
humanfriendly==10.0 \
Mako==1.3.8 \
MarkupSafe==3.0.2 \
mpmath==1.3.0 \
numpy==1.26.4 \
onnx==1.17.0 \
onnx_graphsurgeon==0.5.5 \
onnxruntime==1.20.1 \
packaging==24.2 \
pillow==11.1.0 \
pip==24.3.1 \
platformdirs==4.3.6 \
polygraphy==0.49.18 \
protobuf==6.30.0 \
pycuda==2024.1.2 \
pytools==2025.1.1 \
setuptools==68.1.2 \
sympy==1.13.3 \
tensorrt==10.8.0.43 \
typing_extensions==4.12.2 \
wheel==0.42.0" | xargs pip install
